[package]
name = "rpu"
version = "0.1.0"
edition = "2021"
authors = ["Markus Moenig"]
description = "A procedural retro 3D software renderer and future fantasy console."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#num_cpus = "1.13.1"
vek = { version = "0.15.8", default-features = true, features = ["rgb", "rgba"] }
bytemuck = "1.11.0"