[package]
name = "rpu"
version = "0.1.0"
edition = "2021"
authors = ["Markus Moenig"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#num_cpus = "1.13.1"
vek = { version = "0.14.1", default-features = true, features = ["rgb", "rgba"] }
nalgebra = "0.31.0"
bytemuck = "1.11.0"